### ISSUE TITLE
Support for updates

### ISSUE THREAD

**Issue by ChristianGruen** [james-jw/xq-promise#14]
I didn’t check this out so far by myself… But maybe it will get easier with your new XQuery-based solution to add support for real updates?

**Comment by james-jw** [comment]
It appears we will need a separate fork-join method. Maybe fork-update. Which is annotated as an updating function.  If I try it now, it complains that fork-join must be updating.

Can you expose updating functions from the QueryModule, not sure how to do that.

``` xquery
import module namespace p = 'https://github.com/james-jw/xq-promise';
import module namespace mustache = 'http://xq-mustache';

declare updating function local:add-node($in) {
  db:add('test-fork',<node>{$in}</node>, '/test/' || $in)
};


let $node := <test-element></test-element>
let $promises := 
  for $i in (1 to 100) return
  p:defer(trace(?), $i)
     => p:then(local:add-node(?))
     return p:fork-join($promises)
```

**Comment by ChristianGruen** [comment]
> It appears we will need a separate fork-join method. Maybe fork-update. Which is annotated as an updating function. If I try it now, it complains that fork-join must be updating.

Makes sense!

> Can you expose updating functions from the QueryModule, not sure how to do that.

I’ll check out your current solution and give you feedback soon.

**Comment by ChristianGruen** [comment]
I thought about adding a `async:fork-join-update` function, but as all XQuery 3.1 functions, which are invoking functions, are currently limited to read-only queries, it may be better to postpone this a little.

**Comment by james-jw** [comment]
Yeah, I think that is fine. Fork-join alone still provides an enormous advantage. I haven't had a need for parallel updates yet and since updates are applied at the end anyway, parallel update functions only have a slight advantage over the alternative; construction functions, those that build instead of transform: elements, maps, etc. Which are then applied at the end anyway. 

Glad to see it added to BaseX. Quite awesome!

**Comment by james-jw** [comment]
See BaseX's xquery:fork-join
