### ISSUE TITLE
Promise Module → Async Module?

### ISSUE THREAD

**Issue by ChristianGruen** [james-jw/xq-promise#16]
You convinced me in indicating that the fork-join code is indeed not dependent on the promise pattern, so I’m currently wondering if we should define an `Async Module` (alternative names are welcome), which includes your `promise:fork-join` function, and possibly some more functions based on the ideas that have been developed by @apb2006 and discussed in https://github.com/BaseXdb/basex/issues/1211. Do you think that would make sense? We could e.g. define this module as [W3C EXPath Module](http://expath.org/):

``` xquery
(: Namespace: async = 'http://expath.org/spec/async' :)
async:fork-join($functions as function(*))) as item()*,
async:fork-join($functions as function(*)), $options as map(*)) as item()*
```

Keys allowed for `$options`:
- `threads` (?): number of threads to allow in the pool (default, maybe implementation-defined: number of CPU cores available on the current system) 
- `thread-size` (?): number of functions to be evaluated by each thread (default: `1`)

**Comment by james-jw** [comment]
I think this sounds like a great idea. And as you stated, we could also combine some other great approaches such as those applied in APB's module!

If we could standardize this as well, that would be great!

**Comment by mgaerber** [comment]
Hi guys, I see this is the conversation to my question just sent to the mailing list...

So I'll just give it a try and create a promise with the (other) async:fork-join

**Comment by james-jw** [comment]
See #18
