### ISSUE TITLE
Calling promise fails if worker takes more than one argument

### ISSUE THREAD

**Issue by LukasK** [james-jw/xq-promise#3]
Am I doing something wrong? Or should this indeed work?

``` xquery
let $worker := function($fname, $lname) { 'Hello, ' || $fname || ' ' || $lname }
let $promise := promise:defer($worker, ('James', 'Wright'), map {
  'then': function($p) { 'then: ' || $p },
  'fail': function ($result as item()*) {
            trace($result, 'Request failed!') => prof:void()
          }
})
return $promise(())
```

Result:

```
Evaluating:
Request failed!James
Request failed!Wright
```

Expected:

```
then: Hello, James Wright
```

---

Same problem with a query found in README:

``` xquery
let $req := <http:request method="GET"/>
let $uri := 'http://www.google.com'
let $worker := http:send-request(?, ?)
let $extractListItems := function ($res as map(*)) { $res?list?* }
let $error := function ($result as item()*) {
     trace($result, 'Request failed!') => prof:void()
}
let $retrieve := promise:defer($worker, ($req, $uri), map { 
           'then': parse-json(?), 
           'fail': $error 
}) 
let $extract := $retrieve(map { 'then': $extractListItems  })
return
   $extract(())
```

**Comment by james-jw** [comment]
No that should work and indeed does not. Good find. I have made changes since I wrote those examples especially around how arguments are coerced into the their right place. The fact the fail callback is being called means an exception is being thrown and your fail callback is "catching" it. At least we know that is working! 

Likely a simple bug with the invokeFunctionItem logic of the XQDeferred class which if you look at it could use a good quick refactor. Its not long but overly iffy. 

 I am pretty sure there is an extra `if` in there that is unnecessary. Ill take a look at it over lunch.

**Comment by james-jw** [comment]
Yeah, it appears I broke this when I fixed `when` which you will see has a test that does pass.

Bascially the arity is compared to the work in the function below. The work will always be 1 for a regular defer, but when a `when` is used, the work can be greater than one and this function deals with that, but apparently not properly with a single piece of work that has more than an arity of 1.

Here is the method. It was hacked together as I figured out how to get this working, as you can see with its two sets of if statements. 

`````` xquery
```java
private Value invokeFunctionItem(FItem funcItem, QueryContext qc, InputInfo ii, Value... in) throws QueryException {
    int arity = funcItem.arity();

    if(arity == _work.length && arity > 1) {
      if(in.length == arity) {
        return funcItem.invokeValue(qc, ii, in);
      } else if(in.length == 1) {
        Value args = in[0];
        if(args.size() == 1) {
          return funcItem.invokeValue(qc, ii, args);
        }

        return funcItem.invokeValue(qc, ii, valueToArray(args));
      }
    } else if (funcItem instanceof XqDeferred) {
       // Its a deferred, invoke it with the empty sequence
       return funcItem.invokeValue(qc, ii, XqPromise.empty.value());
    }

    Value out = null;
    if(arity == 0) {
      out = funcItem.invokeValue(qc, ii);
    } else if(arity == 1 && (_work.length > 1 || in.length > 1)) {
      Array results = Array.from(valueToArray(in[0]));
      out = funcItem.invokeValue(qc, ii, results);
    } else {
      out = funcItem.invokeValue(qc, ii, in);
    }

    return out;
 }
``````

I smell an extra if too.

**Comment by LukasK** [comment]
Yes, good candidate for a unit test.

In general, examples in README are a bit out of date/broken. I'll send you a pull request with corrections once I'm through with it.

Thanks for your quick reply! Think you can take a proper lunch break now as you've identified the problem rightaway ;)

**Comment by james-jw** [comment]
This should be fixed: https://github.com/james-jw/xq-promise/commit/14c9f3ef9d1582f45493a445581af0d1760472b6
