### ISSUE TITLE
fail should be provided a map with error information as well as arguments bound.

### ISSUE THREAD

**Issue by james-jw** [james-jw/xq-promise#4]
When a fail callback is called. It should be provided a single argument which is map that contains all the error information.

I propose:

``` xquery
map {
  'err': {
     'description': Same as standard error bindings
     ...
   },
  'args': array [ ... ]
}
```

This way, the fail callback has the information needed to either report a useful error, including the bad arguments or continue the work somehow.

**Comment by james-jw** [comment]
The work function should also be included, in case you want to do a retry.

``` xquery
map {
  'err': {
     'description': Same as standard error bindings
     ...
   },
  'args': array [ ... ]
  'deferred': function#
}
```

**Comment by ChristianGruen** [comment]
Related: [W3 Bugzilla #29264](https://www.w3.org/Bugs/Public/show_bug.cgi?id=29264), proposed by @apb2006.

**Comment by james-jw** [comment]
Fail is now provided a map as proposed by @apb2006!

The additional argument is populated with a map containing the `deferred` and the `arguments`. This will allow a callback to, for example retry if it gets a busy response.

Additionally error handing has been greatly improved. Errors are now properly reported in BaseX, as well as potential bugs. Also, the fail logic has been revised and properly documented in the ReadMe. 

f06b682738d0673037b6ab0deade9011ca252c56

c18ec61edd1c3614e77dbed6027c2a007c04623a
