### ISSUE TITLE
promise:fork

### ISSUE THREAD

**Issue by apb2006** [james-jw/xq-promise#5]
[edited from 1st version]
Hi James,
This is not working the way I am looking for. Am I doing it wrong?

```
import module namespace promise = 'org.jw.basex.async.xq-promise';

let $query := 'prof:sleep(10000),admin:write-log("test1")'
let $promise := promise:fork(xquery:eval(?), $query)
return ( 2,$promise())
```

This does not return until the $query has completed. I want to kick off the query and forget about it.

**Comment by james-jw** [comment]
That certainly should work. Let me take a look, hopefully its not a major flaw.

**Comment by james-jw** [comment]
I read your question wrong. If you don't want to wait for the answer, don't call the promise.

```
let $query := 'prof:sleep(10000),admin:write-log("test1")'
let $promise := promise:fork(xquery:eval(?), $query)
return 2
```

Now, I just tested this and it still waits. I wonder if this is a nuance of the prof:sleep method. Let me try some other stuff.

**Comment by james-jw** [comment]
It appears the ForkJoinPool.invokeAll() method, which returns a list of Futures is blocking, which I wouldn't expect since it returns futures. I confirmed its forking a new thread, but that doesn't help if the main thread is blocked.

Might need to use a different currency approach for the fork method. Was hoping to leverage the existing logic as fork-join...

**Comment by james-jw** [comment]
@apb2006 

That should have done it. The new build is 0.7.4. If you look at the fix, I just added the executor service for the fork calls since the ForkJoinPool methods don't do what we wanted. Since the module was already written with futures in mind very small change.

Thanks for testing and pointing that out!

It now works like I stated. If you want the answer, and are willing to wait, call the promise returned, like you did. 

``` xquery
import module namespace promise = 'org.jw.basex.async.xq-promise';

let $query := 'prof:sleep(10000),admin:write-log("test1")'
let $promise := promise:fork(xquery:eval(?), $query)
return ( 2, $promise())
```

Otherwise, if all you want to do is fork some work, don't call the promise after its returned. The main query thread will continue until its done and report complete. At the same time the forked work is continuing in the background!

``` xquery
import module namespace promise = 'org.jw.basex.async.xq-promise';

let $query := 'prof:sleep(10000),admin:write-log("test1")'
let $promise := promise:fork(xquery:eval(?), $query)
return 2
```

**Comment by ChristianGruen** [comment]
Hi James, I just ran the two code examples on command-line, and I noticed that BaseX terminates. Here is a minimized example:

```
basex "import module namespace promise = 'org.jw.basex.async.xq-promise';promise:fork(function() { })
```

Do you have an idea what might be the reason?

**Comment by james-jw** [comment]
I think your trying to say it 'Doesn't' terminate correct?

I am seeing this too if I use basex directly with the query. If I open a basex prompt and use xquery it works like we expect. 

``` xquery
xquery import module namespace promise = 'org.jw.basex.async.xq-promise';promise:fork(function() {''})
```

So this means the pools or something must be keeping the process alive, which is not noticeable in server, prompt or gui mode, but when run as a script its an issue. Ill do some research tonight, likely a fixable issue. Thanks for testing and pointing that out!

I ran my test last night from the gui, usually I do it from the command prompt. From the command prompt when you do it finishes, but never terminates either, but within the gui or basex cmd prompt it works..
- james

**Comment by ChristianGruen** [comment]
> I think your trying to say it 'Doesn't' terminate correct?

…true ;)

**Comment by apb2006** [comment]
Not sure if this is your situation, but I found if the whole process is closing I need to tell the scheduler to get it clean(ish)
https://github.com/Quodatum/async/blob/master/src/main/content/async.xqm#L89

**Comment by ChristianGruen** [comment]
Some more thoughts (I’m not sure what helps here):
- Simple Threads can be [marked as daemons](http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDaemon%28boolean%29). Daemon threads will be stopped after the main thread has been terminated.
- [Object.finalize](http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#finalize%28%29) could be overwritten as well (but you never know when this function will really be called).
- The canonical solution for finalizing a process in a BaseX query module would be to [implement close() of the QueryResource interface](http://docs.basex.org/wiki/Java_Bindings#Context-Awareness).

**Comment by james-jw** [comment]
I was messing around with finalize but as you stated its not consistent. Two fork-joins in a single query would fail as first would close on second.

I was gonna ask if there was a way to hook into the end of the query! I think I am close!

**Comment by james-jw** [comment]
That was it, will push shortly!

**Comment by james-jw** [comment]
New build is 0.7.5!

**Comment by james-jw** [comment]
When I push from windows the spacing is all off, you guys know how to fix that? I pulled into my ubuntu vm and it looks nice, but if you view the push in github, everything is indented wrong... Still getting used to github, loving it though! 

Anyway, let me know if you guys still have issues. Its seems to have fixed it. I implemented the Interface you suggested Christian and it works like a champ! All test pass and now the pools close immediately once done!

**Comment by james-jw** [comment]
So, one thing to note, in the context of an ongoing JVM such as the GUI or Server etc, this works exactly like we want. For example with RESTXQ, the response will be immediate, and the fork will continue till its done..

When in the context of the terminal however, if you run a query such as:

``` xquery
basex "import module namespace promise = 'org.jw.basex.async.xq-promise';promise:fork(function() { prof:sleep(10000) })
```

The application will not terminate until all forks are done, the query will return immediately, but the terminal will be blocked still.

 As you stated we could mark them to be killed, but then what would be the point of that?

So I think this is as good as it gets for forking outside of starting a new process, which is what you have to do in the context of a terminal to achieve the same 'async' behavior you can within a consistent JVM such as GUI or server mode.

**Comment by apb2006** [comment]
Works for me. What about this one? 

```
import module namespace p = 'org.jw.basex.async.xq-promise';
let $a:=p:fork(function() { prof:sleep(10000),admin:write-log("aa") })
 => p:then(function() {admin:write-log("bb")})
return $a
```

"bb" is never written. However with: 

```
import module namespace p = 'org.jw.basex.async.xq-promise';
let $a:=p:fork(function() { prof:sleep(10000),admin:write-log("aa") })
 => p:then(function() {admin:write-log("bb")})
return $a()
```

"bb" is written but it blocks this thread until all done. 

One features I am looking for my async project is running code after running the fork based on the success/fail result of the fork.

**Comment by james-jw** [comment]
I would expect the first one would work. The result of the second is expected. Nuances to threading I guess. Ill take a look, thanks for checking it out and posting your results.

**Comment by james-jw** [comment]
This is likely a tricky one. But first, you need to queue up the work, then fork, for example:

``` xquery
import module namespace p = 'org.jw.basex.async.xq-promise';
let $a:=p:defer(function() { prof:sleep(10000),admin:write-log("aa") })
 => p:then(function() {admin:write-log("bb")})
return p:fork($a)
```

Now this works! Which is great, but in my testing.... only some % of the time.. Not sure why sometimes it does call the `then`, and sometimes it doesn't...

Every time I debug it, it works... We may have a heisenbug!!

**Comment by james-jw** [comment]
If I add a small thread sleep (10 ms) at the end, it always calls `then`:

``` xquery
import module namespace p = 'org.jw.basex.async.xq-promise';
let $a:=p:defer(function() { prof:sleep(10000),admin:write-log("aa"), prof:sleep(10) })
 => p:then(function() {admin:write-log("bb")})
return p:fork($a)
```

I then did some research and found this:
http://stackoverflow.com/questions/17949317/why-is-my-thread-not-being-notified

**Comment by apb2006** [comment]
I am not really understanding the logic behind this sleep. And the SO link seems short on explanations. 
More importantly maybe this is not the route for me. 
The expectation in my `sync` project is that what is forked will be an updating expression and the `then` or `fail` will run after this is complete. I believe in `xq-promise` this expression should not be updating  This is part of the reason why I am passing strings around - so the optimizing/compiling will occur in the environment after the update has run.

**Comment by ChristianGruen** [comment]
If we want to allows queries to trigger other queries, which are not bound to the original context anymore, @apb2006’s solution may be the only one to go (https://github.com/Quodatum/async/issues/2)…

**Comment by james-jw** [comment]
Thanks for checking this out.

@apb2006, I do not understand the logic either, definitely not something I would rely on without further analysis, but it is certainly interesting and worth sharing.  It has an effect, with the sleep I got 100% success, but only did a handful of tests. Plan to do some more exhaustive testing just to see what comes out of it.

@ChristianGruen, I completely agree and this was not really my intent with xq-promise, but given apb's needs thought it was worth giving a shot.

Instead, the fork method in the promise pattern is really intended for a forking where we want to optimize. This is highly valuable when working with remote resources and REST apis.

For example:

``` xquery
let $dep1 := p:fork($work1)
let $dep2 := p:fork($work2)
return
  p:when(($dep1, $dep2)) 
    => p:then($combine)()
```

**Comment by apb2006** [comment]
Closing this as the original issue is fixed.
I think the use-case `xq-promise` addresses is different from that of `async`. Both have value. Perhaps when both are more mature they can be combined in some way, maybe even in the BaseX core.

**Comment by james-jw** [comment]
I was actually having a similar thought yesterday, are you going to be at XML Prague? If so, It would be great to brainstorm. I agree that with maturity we could to see these libraries
combined and moved into BaseX as maybe the 'async' or 'promise' module! We may not be that long off! If we could find a way to leverage the promise pattern, but with truly async/scheduled execution like your library leverages, it could be highly beneficial.

I think with some additional effort even database update expressions could be parallelized (at least the generation of the update list). I have already started some work on that, but I am pretty busy these next few weeks!

Cheers!

**Comment by apb2006** [comment]
Sadly I wont be at XML Prague this year - a brainstorming session would have been great.  
I will be following the precedings from afar. 
Good luck with your presentations.
