### ISSUE TITLE
Pass on arguments as array

### ISSUE THREAD

**Issue by ChristianGruen** [james-jw/xq-promise#8]
If an array is used for passing on arguments, no flattening would take place. See https://www.w3.org/TR/xpath-functions-31/#func-apply as example for an existing XQuery function…

**Comment by james-jw** [comment]
Completely agree. Thanks for reporting this. I need to improve the argument / function arity coercion logic. In particular it should be more deliberate in how it handles arrays. 

Ill have an update soon.

**Comment by james-jw** [comment]
Example query which replicates this issue

``` xquery
  let $arguments := array { "a", "b", "c" }
  let $promise := promise:defer(fn:concat#3, $arguments)
  return  
    unit:assert-equals("abc", $promise())
```

**Comment by james-jw** [comment]
Had to add code to convert Array to Value[] for passing into a dynamic function invocation.
