### ISSUE TITLE
Add support for EXPath packaging

### ISSUE THREAD

**Issue by james-jw** [james-jw/xq-promise#9]

**Comment by apb2006** [comment]
Hi James,
I had to make one change to `expath-pkg.xml` to get this to work. You have:

```
<package xmlns="http://expath.org/ns/pkg" name="https://github.com/james-jw/xq-promise"
    abbrev="xq-promise" version="0.8.1" spec="1.0">
    <title>XqPromise</title>
    <xquery>
    <namespace>org.jw.basex.async</namespace>
        <file>xq-promise.xqm</file>
    </xquery>
</package>
</package>
```

The `package/xquery/namespace` should be the module namespace i.e `https://github.com/james-jw/xq-promise`

**Comment by james-jw** [comment]
I was wondering what was wrong. I couldn't get it to work either but did
not have much time to really do a deep dive yet

Thanks!
